### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by troke12** [osu-datenshi/hanayo#6]
Daftar To-do
- [ ] password reset error 
- [ ] notif error pada bagian profile
- [ ] reworked clanleaderboard (add relax score)
